### ISSUE TITLE
create staging node based on a P3

### ISSUE THREAD

**Issue by thetechnocrat-dev** [labdao/plex#136]
use PLEx Jupyter Lab
ami-0b9234f816bc23af2

- [x] convert provide-compute.sh script to functions
- [x] add function for installing bacalhau
- [x] add function for running bacalhau
- [x] add function for installing juypter
- [x] add function for running juypter
- [x] add a function to provide-compute.sh that setups a plex-gpu-juypter node
- [x] test script on fresh p3 box
- [x] make AMI for plex-gpu-juypter after running provide-compute.sh setup function
- [x] add a function to provide-compute.sh that runs bacal, ipfs, and juypter daemon
- [x] make sure instance has a stable ip-address (https://aws.amazon.com/premiumsupport/knowledge-center/ec2-associate-static-public-ip/)
- [x] make client able to use STAGE as a selector (default to labdao
- [ ] make a loom of provide sh working and running plex in juypter
- [x] tear down current bacal-prod gpu instance
- [ ] remake bacal gpu instance with 1 TB disk space and use provide-compute-sh
- [ ] reassociate stable-ip address 54.210.19.52

**Comment by NiklasTR** [comment]
feel free to tear down the current P3 to move forward - there might otherwise be some ressource limits in place
