### ISSUE TITLE
Tools not recursively walking down input directories

### ISSUE THREAD

**Issue by acashmoney** [labdao/plex#225]
Sub-directories being missed for IO entries

Example:

pdbbind_processed_size2
├── 6d08
│   ├── 6d08_ligand.sdf
│   └── 6d08_protein_processed.pdb
└── 6qqu
    ├── 6qqu_ligand.mol2
    └── 6qqu_protein_processed.pdb

**Comment by thetechnocrat-dev** [comment]
fixed by https://github.com/labdao/plex/pull/251
