### ISSUE TITLE
add goreleaser check for updated plex version in upgrade.go

### ISSUE THREAD

**Issue by acashmoney** [labdao/plex#278]

**Comment by NiklasTR** [comment]
is this complete?

**Comment by acashmoney** [comment]
Change implemented in monorepo merge (https://github.com/labdao/plex/commit/ae1f784db1d1425f784a3eafaa94cfd844db1d85#diff-b3068b1d57e76f92fcd7b874af628c3bcd49c04600ade8f9532987c62db58294)

Tags which trigger goreleaser workflow now automatically check for CurrentPlexVersion to match tag name
