### ISSUE TITLE
doc animations are not loading

### ISSUE THREAD

**Issue by NiklasTR** [labdao/plex#292]
https://docs.labdao.xyz/getting-started/install-plex

Tested in Chrome and Safari

![image](https://user-images.githubusercontent.com/18559148/234965980-6021c55f-1ce5-4836-a310-4a8220efb0a8.png)

![image](https://user-images.githubusercontent.com/18559148/234966066-82e2d323-1ba8-4d16-88a0-b39fb5e5e5ce.png)

**Comment by acashmoney** [comment]
Solved with #305
