### ISSUE TITLE
Error when building from source - NFT branch

### ISSUE THREAD

**Issue by acashmoney** [labdao/plex#352]
on branch 331

(base) rindtorff@niklas plex % go version         
go version go1.20.4 darwin/arm64
(base) rindtorff@niklas plex % go build           
go: downloading github.com/quic-go/qtls-go1-20 v0.1.0
# github.com/labdao/plex
./upgrade.go:21:1: syntax error: unexpected <<, expected name

**Comment by acashmoney** [comment]
@NiklasTR can you confirm your line 21 in `upgrade.go`?

Should be...

```
	CurrentPlexVersion = "v0.7.3"
```

**Comment by acashmoney** [comment]
@NiklasTR here's the reference Loom video to follow instructions: https://www.loom.com/share/42da5e193dc64dadb934c8957188f3e4

You'll notice we're still using the -tool flag in the current iteration. I've added a ticket for this, though unsure if we get to that this week or next

**Comment by NiklasTR** [comment]
awesome! closing for now
