### ISSUE TITLE
include bacalhau job metadata in IO

### ISSUE THREAD

**Issue by NiklasTR** [labdao/plex#398]
The IO should contain the bacalhau job id. I am not yet sure wether it should contain additional metadata such as the peerID

Usually this content is generated via "bacalhau describe *jobID*"

Link to the user [source](https://www.notion.so/labdao/Early-User-Alexandre-Miloski-b67de9d983054611b1e0e4b3fce0ccad?pvs=4)

**Comment by NiklasTR** [comment]
@thetechnocrat-dev - do you know wether the bacalhau job metadata is stored on IPFS itself? If not, this might be an argument to further expand the scope of the information we are adding to the IO beyond the job-ID itself

**Comment by thetechnocrat-dev** [comment]
new ticket from linear https://github.com/labdao/plex/issues/555
