### ISSUE TITLE
Directory permissions on Windows

### ISSUE THREAD

**Issue by flowscience** [labdao/plex#446]
The install docs instruct to use chmod +x ./plex to update directory perms, but chmod doesn't exist on Windows.

Potential fixes: update docs to suggest user run terminal as admin, or, use [icacls](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc753525(v=ws.10)?redirectedfrom=MSDN) instead of chmod

**Comment by AdamGoyer** [comment]
closed by https://github.com/labdao/plex/pull/451
