### ISSUE TITLE
[LAB-332] use plex create for small molecule docking tutorial

### ISSUE THREAD

**Issue by acashmoney** [labdao/plex#547]
* [ ] update inputs to use local files
* [ ] `plex_create` instead of `plex_init`
* [ ] modify colab notebook
* [ ] modify code blocks on docs tutorial page

<sub>From [SyncLinear.com](https://synclinear.com) | [LAB-332](https://linear.app/convexitylabs/issue/LAB-332/use-plex-create-for-small-molecule-docking-tutorial)</sub>

**Comment by acashmoney** [comment]
I think we should use explicit file paths wherever possible. We can also point out that the tool can handle full directories of files in a separate code block in the bottom

**Comment by acashmoney** [comment]
Duplicate issue to #546

**Comment by NiklasTR** [comment]
testing user identity again
