### ISSUE TITLE
[LAB-336] API reference for pip pkg

### ISSUE THREAD

**Issue by acashmoney** [labdao/plex#552]
Currently we include notebook tutorials in our docs to demonstrate how users can interact with the plex pip package. However, we lack an API reference section which outlines which functions are available and the arguments they accept.

Given the pip pkg is still changing, we should aim for an MVP API reference section which outlines the "core" functions.

* [ ] draft api reference section
* [ ] propose changes to current pip function specs
* [ ] implement above changes
* [ ] update public-facing notebooks
* [ ] push changes to docs

<sub>From [SyncLinear.com](https://synclinear.com) | [LAB-336](https://linear.app/convexitylabs/issue/LAB-336/api-reference-for-pip-pkg)</sub>

**Comment by thetechnocrat-dev** [comment]
V2:

[https://www.notion.so/labdao/6ebc9b59e0d74eeabb391d624f500424?v=2540e4f2e24f4ae597f624d30c7f1068&p=5a7284921c7c4e9692e4ea6d0e3d1922&pm=s](https://www.notion.so/labdao/6ebc9b59e0d74eeabb391d624f500424?v=2540e4f2e24f4ae597f624d30c7f1068&p=5a7284921c7c4e9692e4ea6d0e3d1922&pm=s)

**Comment by acashmoney** [comment]
@NiklasTR updated api reference here: [https://docs-git-552-lab-336-api-reference-for-pip-pkg-labdao.vercel.app/reference/python](https://docs-git-552-lab-336-api-reference-for-pip-pkg-labdao.vercel.app/reference/python)
