### ISSUE TITLE
[LAB-341] peer-id implemented user on plex go client

### ISSUE THREAD

**Issue by acashmoney** [labdao/plex#554]
<sub>From [SyncLinear.com](https://synclinear.com) | [LAB-341](https://linear.app/convexitylabs/issue/LAB-341/peer-id-implemented-user-on-plex-go-client)</sub>

**Comment by acashmoney** [comment]
testing

**Comment by acashmoney** [comment]
testing comments through linear

**Comment by acashmoney** [comment]
testing through github

**Comment by thetechnocrat-dev** [comment]
hello world
