### ISSUE TITLE
[LAB-389] PLEX_INIT does not handle relative filepaths

### ISSUE THREAD

**Issue by NiklasTR** [labdao/plex#560]
```
from plex import CoreTools, plex_init


initial_io_cid = plex_init(

 CoreTools.EQUIBIND.value,

 protein="/content/6d08_protein_processed.pdb",

 small_molecule="/content/6d08_ligand.sdf",

)
```

This code does not run in my hands - is there an obvious error?

[https://colab.research.google.com/drive/15nZrm5k9fMdAHfzpR1g_8TPIz9qgRoys?usp=sharing#scrollTo=ZT2weQliNeGX](https://colab.research.google.com/drive/15nZrm5k9fMdAHfzpR1g_8TPIz9qgRoys?usp=sharing#scrollTo=ZT2weQliNeGX)

<sub>From [SyncLinear.com](https://synclinear.com) | [LAB-389](https://linear.app/convexitylabs/issue/LAB-389/plex-init-does-not-handle-relative-filepaths)</sub>

**Comment by NiklasTR** [comment]
The below works. The bug in your example occurs because if there is exactly "/" in the file path the program incorrectly assumes a CID path was passed.

```
from plex import CoreTools, plex_init

# small_molecule_path = ["QmV6qVzdQLNM6SyEDB3rJ5R5BYJsQwQTn1fjmPzvCCkCYz/ZINC000003986735.sdf"]
# protein_path = ["QmUWCBTqbRaKkPXQ3M14NkUuM4TEwfhVfrqLNoBB7syyyd/7n9g.pdb"]

small_molecule_path = ["/content/testdata/6d08_ligand.sdf"]
protein_path = ["/content/testdata/6d08_protein_processed.pdb"]


initial_io_cid = plex_init(
    CoreTools.EQUIBIND.value,
    protein=protein_path,
    small_molecule=small_molecule_path,
)

completed_io_cid, io_local_filepath = plex_run(initial_io_cid)
```

**Comment by thetechnocrat-dev** [comment]
exact line causing the bug [https://github.com/labdao/plex/blob/6e9f37f29218a2abd4a30405a70b86c8c5d1d354/cmd/init.go#L165](https://github.com/labdao/plex/blob/6e9f37f29218a2abd4a30405a70b86c8c5d1d354/cmd/init.go#L165)
