### ISSUE TITLE
[LAB-623] web3auth on gateway frontend

### ISSUE THREAD

**Issue by acashmoney** [labdao/plex#665]
<sub>From [SyncLinear.com](https://synclinear.com) | [LAB-623](https://linear.app/convexitylabs/issue/LAB-623/web3auth-on-gateway-frontend)</sub>

**Comment by thetechnocrat-dev** [comment]
Excited for this one! 🕸️ 3

**Comment by acashmoney** [comment]
This is replaced in favor of [LAB-661](https://linear.app/convexitylabs/issue/LAB-661/replace-web3auth-with-privy)
