### ISSUE TITLE
change the command line messages to make them more simple and instructive

### ISSUE THREAD

**Issue by NiklasTR** [labdao/plex#82]
The proposed changes include:

- [x] When displaying the additional information - rename the ### Heading to something like "Additional Configuration Information:"
- [x] When search in the input directory: "Searching for files in input directory"
- [x] When completing the job - 'open this directory on your Mac by calling "open path/to/results"'
- [ ] Notify user about the expected runtime for an app - this could be a parameter in the app.jsonl "Average run time is about 15 minutes" > in the app.json
- [ ] restructure output directory to contain, (1) /inputs, (2) /outputs, (3)  /metadata (this would include additional bacalhau info and index.csv etc.)

**Comment by NiklasTR** [comment]
adding Loom: https://www.loom.com/share/3e1573cb07dc47f58f908abb7a77863a

**Comment by acashmoney** [comment]
@NiklasTR first three changes are completed as of 4d432c96cf2154f0658ed1c46dfdc2f248d30956

On the final change, the output directory isn't being written anymore on my local machine. Tested by switching to from current working branch to `main`, and I get the same issue. This could be an issue with our bacalhau node? 

Can you try running the test command on your machine and let me know if you still see a completed job directory?

**Comment by NiklasTR** [comment]
Most likely the pinning function will have to add job-dir/inputs, not job/dir (what is happening right now)

**Comment by NiklasTR** [comment]
@acashmoney - is this still an issue?

**Comment by NiklasTR** [comment]
moving this back in prio given current wave of bugs

**Comment by thetechnocrat-dev** [comment]
stale
