### ISSUE TITLE
Bacalhau not installing, when using tutorial install script

### ISSUE THREAD

**Issue by NiklasTR** [labdao/plex#89]
Hey everyone, Bacalhau isn't installing. Here's a quick loom of the issue:

https://www.loom.com/share/d4472a722d364606be4b89dd7a3a69f5

**Comment by mithrauki** [comment]
It runs, despite the installation error.

Nik says: let's drop bacalhau dependency to avoid the error message (now we're using the Go package directly).

**Comment by thetechnocrat-dev** [comment]
https://github.com/labdao/plex/pull/130 will close this issue
