### ISSUE TITLE
go build distribution package

### ISSUE THREAD

**Issue by NiklasTR** [labdao/plex#95]
Pre-built binaries live in `plex` currently. We want to create a GitHub action (or something similar) that runs the build script `plex/build.sh` and hosts the binaries outside of the repo.

We will need to change the curl links in `plex/install.sh` to point to wherever we host these

Package registry for hosting: https://github.com/features/packages

Store the .tar files with the permissions by default so user doesn't need to chmod

**Comment by acashmoney** [comment]
[Go Releaser](https://github.com/goreleaser/goreleaser) to be integrated into GH Action

**Comment by acashmoney** [comment]
[PR](https://github.com/labdao/plex/pull/102) opened
